INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'acid', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'spray', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'low energy light lamp', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'lamp', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'halogen light lamp', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'phone book', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'home appliance', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plate', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'laundry detergent', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'aluminium container', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plastic container', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'polystyrene container', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'car battery', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'empty motor oil bottle', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'glass jar', r.id FROM recyclable_status r WHERE r.name = 'glass';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'egg carton', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plastic egg carton', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'camembert box', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'tin', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'cereal box', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'pizza box', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'spray paint can', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'shaving cream can', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'syrup bottle', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plastic oil bottle', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'glass oil bottle', r.id FROM recyclable_status r WHERE r.name = 'glass';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plastic bottle', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'glass bottle', r.id FROM recyclable_status r WHERE r.name = 'glass';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'branches', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'food carton', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'wood crate', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'notebook', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'spiral notebook', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'can', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'carton', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'ink cartidge', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'cassette tape', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'cd', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'file', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'cotton swab', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'baby diaper', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'metal lid', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'toothpaste (tube)', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'dvd', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'envelope', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'window envelope', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'peelings', r.id FROM recyclable_status r WHERE r.name = 'compost-pile';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'faience', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'foliage', r.id FROM recyclable_status r WHERE r.name = 'compost-pile';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plastic wrap', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'household product bottle', r.id FROM recyclable_status r WHERE r.name = 'recyclable-if-empty';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'dish soap', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'shampoo bottle', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'grass', r.id FROM recyclable_status r WHERE r.name = 'glass';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plastic cup', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'rubble', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'wire mesh', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'motor oil', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'toy', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'newspaper', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'wool', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'glass wool', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'litter', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'book', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'magazine', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'mattress', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'furniture', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'mirror', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'carpet', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'neon', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'terracotta', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'computer', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'paper', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'paper towel', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'tinfoil', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'gift wrap', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'wallpaper', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'battery', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plank of wood', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plant', r.id FROM recyclable_status r WHERE r.name = 'compost-pile';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'glass dish', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'tire', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'polystyrene', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'porcelain', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'pot of cream', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'paint bucket', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'yoghurt pot', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'glass pot', r.id FROM recyclable_status r WHERE r.name = 'glass';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'pottery', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'beauty product', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'crop protection product', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'radiograph', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'disposable shaver', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'fridge', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'food leftovers', r.id FROM recyclable_status r WHERE r.name = 'compost-pile';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'journal', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'paper bag', r.id FROM recyclable_status r WHERE r.name = 'recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'plastic bag', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'solvent', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'pen', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'tree trimmings', r.id FROM recyclable_status r WHERE r.name = 'compost-pile';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'mercury thermometer', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'tube (cream, toothpaste)', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'fluorescent lamp', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'hose', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'kitchen tool', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'dishes', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'bicycle', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'damaged clothing', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'window pane', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'eau gazeuse', r.id FROM recyclable_status r WHERE r.name = 'recyclable-if-empty';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'eau minérale', r.id FROM recyclable_status r WHERE r.name = 'recyclable-if-empty';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'carte mémoire flash', r.id FROM recyclable_status r WHERE r.name = 'container';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'ballon de foot', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'lait en poudre', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'filtre à huile', r.id FROM recyclable_status r WHERE r.name = 'waste-collection-center';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'cendrier', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'coca cola', r.id FROM recyclable_status r WHERE r.name = 'recyclable-if-empty';
INSERT INTO visual_class (id, name, recyclable_status_id) SELECT UUID(), 'éponge à gratter', r.id FROM recyclable_status r WHERE r.name = 'not-recyclable';

INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'acide ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'acid';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'aérosol' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'spray';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'ampoule basse consommation' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'low energy light lamp';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'ampoule classique' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'lamp';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'ampoule halogène' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'halogen light lamp';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'annuaire ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'phone book';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'appareil électroménager' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'home appliance';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'assiette ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plate';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'baril de lessive' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'laundry detergent';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'barquette en aluminium' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'aluminium container';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'barquette plastique' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plastic container';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'barquette polystyrène' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'polystyrene container';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'batterie de voiture' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'car battery';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bidon d''huile moteur vide' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'empty motor oil bottle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bocal en verre' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'glass jar';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'boîte à oeufs en carton' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'egg carton';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'boîte à oeufs en plastique' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plastic egg carton';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'boîte camembert' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'camembert box';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'boîte de conserve' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'tin';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'boîte de céréales' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'cereal box';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'boîte de pizza' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'pizza box';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bombe de peinture' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'spray paint can';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bombe mousse a raser' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'shaving cream can';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bouteille de sirop' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'syrup bottle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bouteille d''huile plastique' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plastic oil bottle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bouteille d''huile verre' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'glass oil bottle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bouteille en plastique' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plastic bottle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'bouteille en verre ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'glass bottle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'branchage' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'branches';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'brique alimentaire' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'food carton';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'cagette bois' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'wood crate';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'cahier' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'notebook';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'cahier à spirales' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'spiral notebook';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'canette' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'can';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'carton' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'carton';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'cartouche d''encre' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'ink cartidge';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'cassette' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'cassette tape';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'cd' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'cd';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'classeur' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'file';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'coton tige' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'cotton swab';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'couche bébé' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'baby diaper';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'couvercle en métal' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'metal lid';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'dentifrice (tube)' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'toothpaste (tube)';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'dvd' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'dvd';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'enveloppe' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'envelope';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'enveloppe à fenêtre' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'window envelope';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'épluchures' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'peelings';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'faïence' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'faience';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'feuillage' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'foliage';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'film plastique' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plastic wrap';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'flacon produit ménager' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'household product bottle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'flacon de liquide vaisselle' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'dish soap';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'flacon de shampoing' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'shampoo bottle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'gazon' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'grass';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'gobelet plastique' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plastic cup';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'gravats' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'rubble';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'grillage' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'wire mesh';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'huile de vidange' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'motor oil';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'jouet' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'toy';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'journaux' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'newspaper';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'laine' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'wool';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'laine de verre' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'glass wool';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'litière pour animaux' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'litter';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'livre' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'book';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'magazine' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'magazine';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'matelas' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'mattress';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'meuble' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'furniture';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'miroir' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'mirror';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'moquette' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'carpet';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'néon' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'neon';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'objet en terre cuite' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'terracotta';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'ordinateur' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'computer';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'papier' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'paper';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'papier absorbant' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'paper towel';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'papier aluminium' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'tinfoil';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'papier cadeau' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'gift wrap';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'papier peint' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'wallpaper';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'pile' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'battery';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'planche de bois' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plank of wood';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'plante' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plant';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'plat en verre' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'glass dish';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'pneu' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'tire';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'polystyrène' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'polystyrene';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'porcelaine' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'porcelain';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'pot de crème fraîche' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'pot of cream';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'pot de peinture' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'paint bucket';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'pot de yaourt ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'yoghurt pot';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'pot en verre' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'glass pot';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'poterie' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'pottery';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'produit de beauté ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'beauty product';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'produit phytosanitaire' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'crop protection product';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'radiographie' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'radiograph';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'rasoir jetable' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'disposable shaver';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'réfrigérateur ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'fridge';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'restes de repas' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'food leftovers';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'revue' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'journal';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'sac en papier' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'paper bag';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'sac plastique' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'plastic bag';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'solvant' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'solvent';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'stylo' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'pen';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'taille d''arbre ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'tree trimmings';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'thermomètre à mercure' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'mercury thermometer';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'tube (crème, dentifrice)' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'tube (cream, toothpaste)';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'tube fluorescent' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'fluorescent lamp';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'tuyau d''arrosage' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'hose';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'ustensile de cuisine' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'kitchen tool';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'vaisselle' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'dishes';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'vélo' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'bicycle';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'vêtement en mauvais état ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'damaged clothing';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'vitre ' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'window pane';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'soda water' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'eau gazeuse';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'mineral water' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'eau minérale';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'flash memory' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'carte mémoire flash';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'soccer ball' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'ballon de foot';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'powdered milk' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'lait en poudre';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'oil filter' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'filtre à huile';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'ashtray' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'cendrier';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'coca cola' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'coca cola';
INSERT INTO visual_class_translation(id, translation_locale_id, visual_class_id, text) SELECT UUID(), t.id, v.id, 'scouring pad' FROM translation_locale t, visual_class v WHERE t.name = 'fr' AND v.name = 'éponge à gratter';
